### ISSUE TITLE
Rendering is weird in game

### ISSUE THREAD

**Issue by Sunconure11** [MinerArcana/Runecarved#13]
![screenshot 2018-07-09 01 42 13](https://user-images.githubusercontent.com/5614902/42432617-6117ee80-8319-11e8-9ec9-fd6bf5aa0cf1.png)

**Comment by Sunconure11** [comment]
This is related to the newest build of Forge.

**Comment by FreneticScribbler** [comment]
Ah okay, I'll look into that, thanks for the heads up.

**Comment by Sunconure11** [comment]
@warlordjones Here's how Waystones fixed it.

https://github.com/blay09/Waystones/issues/126

**Comment by FreneticScribbler** [comment]
Hmhm. Thanks for the heads up! That change might have broken BASE, not just RC. Investigating.

**Comment by Divineaspect** [comment]
poke

**Comment by FreneticScribbler** [comment]
Oh yeah - this is now fixed
