### ISSUE TITLE
kicked by internal server error when interacting with Rudimentary Enchanter on server

### ISSUE THREAD

**Issue by Darkmega18** [MinerArcana/Runecarved#14]
Internal server errored out of the server when trying to interact with the runecarved enchantment table. Multicraft threw this in the console but the server never actually fully crashed from it. (it's bottom to top since thats how multi does it's console. newest to oldest)

`12.07 21:15:37 [Disconnect] User Darkmega18 has disconnected, reason: unknown 12.07 21:15:37 [Multicraft] Skipped 196 lines due to rate limit (30/s) 12.07 21:15:16 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161] 12.07 21:15:16 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] 12.07 21:15:16 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.Gui 12.07 21:15:16 [Server] INFO ... 5 more 12.07 21:15:16 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?] 12.07 21:15:16 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_161] 12.07 21:15:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_161] 12.07 21:15:16 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?] 12.07 21:15:16 [Server] INFO at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:875) ~[ForgeHooks.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[ahb.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180) ~[ahb.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.world.World.func_180501_a(World.java:342) ~[amu.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:623) ~[axw.class:?] 12.07 21:15:16 [Server] INFO at com.minerarcana.runecarved.block.BlockSimpleEnchanter.createTileEntity(BlockSimpleEnchanter.java:68) ~[BlockSimpleEnchanter.class:?] 12.07 21:15:16 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui 12.07 21:15:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161] 12.07 21:15:16 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?] 12.07 21:15:16 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?] 12.07 21:15:16 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_161] 12.07 21:15:16 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_161] 12.07 21:15:16 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/Gui 12.07 21:15:16 [Server] Server thread/FATAL Error executing task`

**Comment by FreneticScribbler** [comment]
Welp. Classic client/server derp. 

Tangentially, that's an odd way of doing a console...

**Comment by Darkmega18** [comment]
yeah, it goes bottom to top so that the newest is on the top when you come in. but it makes reading it awkward compared to other consoles and general reading conventions. :V

**Comment by Darkmega18** [comment]
will the mod be updated anytime soon so that I can add it back to the server so to test?
