### ISSUE TITLE
Shift click to place items in/out of Simple Enchanter crashes game.

### ISSUE THREAD

**Issue by VallenFrostweaver** [MinerArcana/Runecarved#9]
Shift click to place items in/out of Simple Enchanter crashes game.

**Comment by SkySom** [comment]
Does it give a crash log?

**Comment by VallenFrostweaver** [comment]
Yup. https://pastebin.com/AvYcTGJn
I wanted to report it and got interrupted. Sorry about that.

**Comment by FreneticScribbler** [comment]
See #7. Should have tagged with fixed in dev rather than closed. My mistake.

**Comment by SkySom** [comment]
Should have just put a hotfix on Curse 🗡

**Comment by FreneticScribbler** [comment]
I didn't think it'd be necessary because I wasn't expecting 1.1.0 to take this long o.O

**Comment by FreneticScribbler** [comment]
(Fixed in 1.1.0 and I forgot to close this when releasing)
